python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.02 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.05 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.08 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.10 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.20 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.30 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.40 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.50 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.60 --seed 39 --save_name cite_best_dgi.pkl --gpu 5

python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.02 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.05 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.08 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.10 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.20 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.30 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.40 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.50 --seed 39 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.60 --seed 39 --save_name cite_best_dgi.pkl --gpu 5

python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.02 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.05 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.08 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.10 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.20 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.30 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.40 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.50 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type node --drop_percent 0.60 --seed 31 --save_name cite_best_dgi.pkl --gpu 5

python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.02 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.05 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.08 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.10 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.20 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.30 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.40 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.50 --seed 31 --save_name cite_best_dgi.pkl --gpu 5
python -u execute.py --dataset citeseer --aug_type subgraph --drop_percent 0.60 --seed 31 --save_name cite_best_dgi.pkl --gpu 5